Vagrant.configure("2") do |config|
  config.vm.define "snort" do |snort|
    snort.vm.box = "ubuntu/focal64"
    snort.vm.hostname = "snort"
    snort.vm.network "public_network"
  end

  config.vm.define "kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "kali"
    kali.vm.network "public_network"
  end
end
